# Generated by Django 5.1.3 on 2025-07-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeinscription',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='antecedents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='informations_complementaires',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='personne_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='telephone_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
