# Generated by Django 5.1.3 on 2025-07-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0002_demandeinscription_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeinscription',
            name='personne_contact',
        ),
        migrations.RemoveField(
            model_name='demandeinscription',
            name='telephone_contact',
        ),
    ]
