# Generated by Django 5.1.3 on 2025-07-22 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0003_remove_demandeinscription_personne_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonneAPrevenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnes_a_prevenir', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
