# Generated by Django 5.1.3 on 2025-07-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0005_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='mot_de_passe_temporaire',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
