# Generated by Django 5.1.3 on 2025-08-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0007_medecin_photo_rendezvous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='medecin',
        ),
    ]
