# Generated by Django 5.1.3 on 2025-08-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0008_remove_rendezvous_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppMedical.medecin'),
        ),
    ]
