# Generated by Django 5.1.3 on 2025-08-04 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0009_rendezvous_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppMedical.hopital'),
        ),
    ]
