# Generated by Django 5.1.3 on 2025-08-07 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0010_rendezvous_hopital'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.FloatField(blank=True, help_text='En kg', null=True)),
                ('taille', models.FloatField(blank=True, help_text='En cm', null=True)),
                ('tension_arterielle', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature', models.FloatField(blank=True, help_text='En °C', null=True)),
                ('frequence_cardiaque', models.PositiveIntegerField(blank=True, null=True)),
                ('observations_generales', models.TextField(blank=True, null=True)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('examens', models.TextField(blank=True, null=True)),
                ('traitements_en_cours', models.TextField(blank=True, null=True)),
                ('prescriptions', models.TextField(blank=True, null=True)),
                ('fichiers', models.FileField(blank=True, null=True, upload_to='dossiers/')),
                ('date_ouverture', models.DateField(auto_now_add=True)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
