# Generated by Django 5.1.3 on 2025-08-08 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0011_dossiermedical'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='patients',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'patient'}, related_name='medecins_assignés', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DossierMedical',
        ),
    ]
