# Generated by Django 5.1.3 on 2025-08-09 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0012_medecin_patients_delete_dossiermedical'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5, null=True)),
                ('antecedents', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('infos_complementaires', models.TextField(blank=True, null=True)),
                ('poids', models.FloatField(blank=True, help_text='En kg', null=True)),
                ('taille', models.FloatField(blank=True, help_text='En cm', null=True)),
                ('tension_arterielle', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature', models.FloatField(blank=True, help_text='En °C', null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('examens', models.TextField(blank=True, null=True)),
                ('traitements', models.TextField(blank=True, null=True)),
                ('prescriptions', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='dossiers/')),
                ('date_suivi', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_medical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
