# Generated by Django 5.1.3 on 2025-08-10 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0013_dossiermedical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='date_suivi',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='examens',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='prescriptions',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='tension_arterielle',
        ),
        migrations.RemoveField(
            model_name='dossiermedical',
            name='traitements',
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='groupe_sanguin',
            field=models.CharField(default=3, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SuiviMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taille', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tension_arterielle', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('examens', models.TextField(blank=True, null=True)),
                ('traitements', models.TextField(blank=True, null=True)),
                ('prescriptions', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='dossiers/')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='AppMedical.dossiermedical')),
            ],
        ),
    ]
