# Generated by Django 5.1.3 on 2025-08-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0014_remove_dossiermedical_date_suivi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivimedical',
            name='fichier',
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='groupe_sanguin',
            field=models.CharField(default='Inconnu', max_length=3),
        ),
        migrations.CreateModel(
            name='FichierSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichiers', models.FileField(upload_to='dossiers/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='AppMedical.suivimedical')),
            ],
        ),
    ]
