# Generated by Django 5.1.3 on 2025-08-12 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0015_remove_suivimedical_fichier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichiersuivi',
            name='fichiers',
            field=models.FileField(upload_to='suivis/'),
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMedical.medecin')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentPrescrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='Ex: 500mg', max_length=100)),
                ('frequence', models.CharField(help_text='Ex: 2 fois par jour', max_length=100)),
                ('duree', models.CharField(help_text='Ex: 7 jours', max_length=100)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='AppMedical.ordonnance')),
            ],
        ),
    ]
