# Generated by Django 5.1.3 on 2026-03-28 11:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0016_alter_fichiersuivi_fichiers_ordonnance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['-date', '-heure']},
        ),
        migrations.RemoveField(
            model_name='demandeinscription',
            name='approuvee',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='mot_de_passe_temporaire',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='AppMedical.hopital'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='demandeinscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppMedical.hopital'),
        ),
        migrations.AddField(
            model_name='hopital',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hopital',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('medecin', 'Médecin'), ('admin_hopital', 'Admin Hôpital'), ('admin_system', 'Admin Système')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'role': 'admin_hopital'}, on_delete=django.db.models.deletion.CASCADE, related_name='hopital_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
