# Generated by Django 5.1.3 on 2026-04-09 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMedical', '0017_alter_rendezvous_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopital',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hopital',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de confirmation'), ('confirme', 'Confirmé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('medecin', 'Médecin'), ('admin_hopital', 'Admin Hôpital'), ('admin_system', 'Admin Système'), ('livreur', 'Livreur')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin_hopital'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hopital_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permis_conduire', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicule', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_livraison', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('actif', 'Actif'), ('suspendu', 'Suspendu')], default='en_attente', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
